### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by ymage**
Fix format placeholder

### CODE REVIEW

**Comment by ghickman** [comment]
@ymage – could you explain your fix a bit more please?  For instance I'm not sure why this change is necessary.  A link to a docs page where I can read more would be great if you can find one.

**Comment by ymage** [comment]
Well, 

For instance, when the %s is matching a N number, the debug statement give a 
`Specified Neason digits` instead of `Specified N season digits`

That's because you have a "**% s**eason" instead of "**%s** season"

That's all.

**Comment by ghickman** [comment]
@ymage – thanks for the explanation and the fix, much appreciated!

**Comment by ghickman** [comment]
This is released in 4.3.1 on the [PyPI](https://pypi.python.org/pypi/tvrenamr)

**Pull request merged**
